org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Mod Properties
maven_group=com.example
archives_base_name=addon-template

# Dependencies Specs
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.1
loader_version=0.16.5
meteor_version=0.5.8
